[assembly: System.Reflection.AssemblyProduct("Rox.Xamarin.Video")]
[assembly: System.Reflection.AssemblyCompany("Rox Software Pty Ltd")]
[assembly: System.Reflection.AssemblyCopyright("©2016 Rox Software Pty Ltd")]
[assembly: System.Reflection.AssemblyDescription("https://www.rox.software/")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Resources.NeutralResourcesLanguage("en")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]